### ISSUE TITLE
Mac DMG quits immediately after opening 

### ISSUE THREAD

**Issue by mdegenero** [maltfield/cross-platform-python-gui#1]
Hi @maltfield --

I ran the application through to create executables, but when I tried to open the dmg from helloWorld-mac-x86_64, it immediately quits after opening. It doesn't look like there were any errors outputted with the PyInstaller command. Do you know what might be causing this issue? 

My project contains two python files and a .kv file, as well as a few .pngs. I can upload any relevant logs or files, if that will help.

**Comment by maltfield** [comment]
It quits after opening the `.dmg` or the `.app`? It can happen after opening the `.app`  from the GUI. My best-guess is that it's an issue with (lack of) notarization.

What version of MacOS are you running?

Please link me to the relevant GitHub Actions output.

Try opening the executable directly using the command-line to see if it produces additional output.

```
open -W helloWorld.dmg
open -W /Volumes/helloWorld/helloWorld.app/Contents/MacOS/helloWorld
```

**Comment by maltfield** [comment]
Wait, where's your python files? You need a `main.py` at least..

 * https://github.com/mdegenero/cross-platform-python-gui/tree/master/src

If you want another example to look at how your `src/` dir should be, see

 * https://github.com/BusKill/buskill-app/tree/master/src

**Comment by mdegenero** [comment]
My bad, I had made a few changes and forgot to re-upload them. Just ran through the Actions again: https://github.com/mdegenero/cross-platform-python-gui/runs/962485463?check_suite_focus=true. 

My computer will not allow me to open HelloWorld.app, because it "is from an unidentified developer." Is there a workaround for this?

**Comment by mdegenero** [comment]
My bad, I had made a few changes and forgot to re-upload. Just ran through the Actions again: https://github.com/mdegenero/cross-platform-python-gui/runs/962485463?check_suite_focus=true

When I try to open helloWorld.app, I get the following error:   

File "virtual_ensemble.py", line 38, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

**Comment by maltfield** [comment]
I see you've already added numpy to your `requirements.txt` file, and the output from the Actions you linked-to shows that it *is* being installed.

 * https://github.com/mdegenero/cross-platform-python-gui/blob/master/requirements.txt

What I don't understand is why both `main.py` and `virtual_ensemble.py` import numpy, yet the error you get is only for `virtual_ensemble.py`, which--if numpy is truly missing--it should error-out on `main.py` first.

`PyInstaller` should clearly be able to find your `numpy` imports, but try adding it explicitly by adding it to `hiddenimports`

 * https://github.com/mdegenero/cross-platform-python-gui/blob/892ba4378dd13b924a63634cd5154b307aeeffd2/build/mac/buildDmg.sh#L86

Change

```
hiddenimports=['pkg_resources.py2_warn'],
```

to

```
hiddenimports=['pkg_resources.py2_warn', 'numpy'],
```

If that doesn't work, try googling for `PyInstaller` issues and this error message. If you find a solution, please post back here so others can benefit from it.

**Comment by mdegenero** [comment]
I added the line "pip install --user --upgrade --force-reinstall numpy" to the buildDmg.sh file and that seemed to get rid of the numpy error. I am now getting a similar error, but for matplotlib: 

"ModuleNotFoundError: No module named 'matplotlib'"

**Comment by mdegenero** [comment]
Out of curiosity, I took out the 'matplotlib' import. It seems to be throwing the same error for every python import in the virtual_ensemble.py file.

**Comment by mdegenero** [comment]
So, I got the same "ModuleNotFoundError" for all of my Python imports; so I added the --force-reinstall command for all of those imports, manually, in the buildDmg.sh file. I am now getting the following error: 

```
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    import virtual_ensemble as vmet
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/Users/runner/Library/Python/3.8/lib/python/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "virtual_ensemble.py", line 51, in <module>
    import moviepy.editor as mp
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/Users/runner/Library/Python/3.8/lib/python/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "moviepy/editor.py", line 60, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/Users/runner/Library/Python/3.8/lib/python/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "moviepy/video/io/sliders.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/Users/runner/Library/Python/3.8/lib/python/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "matplotlib/__init__.py", line 898, in <module>
  File "matplotlib/cbook/__init__.py", line 480, in _get_data_path
  File "matplotlib/__init__.py", line 239, in wrapper
  File "matplotlib/__init__.py", line 534, in get_data_path
  File "matplotlib/__init__.py", line 239, in wrapper
  File "matplotlib/__init__.py", line 563, in _get_data_path
NameError: name 'defaultParams' is not defined
```

**Comment by maltfield** [comment]
> added the line "pip install --user --upgrade --force-reinstall numpy" to the buildDmg.sh file and that seemed to get rid of the numpy error

I updated the `buildDmg.sh` script to use the `--force-reinstall` command when installing the depends listed in `requirements.txt` -- please test to see if this fixes your issues without having to add your modules one-by-one to the `buildDmg.sh` file

https://github.com/maltfield/cross-platform-python-gui/commit/ec275a1c52286a38f9a5837bc3cf982b806515ba#diff-5a0e140a72dc4932aaac93f01edb0b62R66

**Comment by maltfield** [comment]
> NameError: name 'defaultParams' is not defined

As for this, first confirm that your code itself doesn't have errors by running `pythonX main.py` before the build.

And if this is PyInstaller-specific, then please search the internet for the error and update this ticket with your findings for the benefit of others

 * https://duckduckgo.com/?q="NameError%3A+name+'defaultParams'+is+not+defined"+"pyinstaller"
 * https://github.com/pyinstaller/pyinstaller/issues/5004
 * https://stackoverflow.com/questions/63163027/how-to-use-pyinstaller-with-matplotlib-in-use
 * etc

**Comment by maltfield** [comment]
Closing this. Please re-open if this is indeed an issue with this repo.

And please add comments if you solved your issues with PyInstaller/matplotlib
